In [1]:
import pandas as pd
import os
import numpy as np
from tqdm import tqdm_notebook as tqdm
import joblib
pd.set_option('display.max_columns', None)
root = '../data/phase_2/raw/other/'
os.listdir(root)

['Aroma-1 Unit 000 Split_Factor Calculation.xlsx',
 'FCFC Import Naphtha Composition Lab_001~100_R2.xlsx',
 '附件一.xlsx',
 '附件二.xlsx']

In [2]:
y_cols = ['C5NP','C5IP','C5N',
           'C6NP','C6IP','C6N','C6A',
           'C7NP','C7IP','C7N','C7A',
           'C8NP','C8IP','C8N','C8A',
           'C9NP','C9IP','C9N','C9A',
           'C10NP','C10IP','C10N','C10A']

# load dataset

In [3]:
df = pd.read_excel(root+'FCFC Import Naphtha Composition Lab_001~100_R2.xlsx',sheet_name='001~100')
df = df.dropna(axis=0,how='all')
df = df.dropna(axis=1,how='all')
df = df.reset_index(drop=True)
df.columns = [i for i in range(df.shape[1])]

# y23

In [4]:
y23 = df.loc[33:33+22,1:].reset_index(drop=True).set_index(1).T.reset_index(drop=True).head(23).astype('float')
y23.columns = y_cols

In [5]:
y23.head(3)

,C5NP,C5IP,C5N,C6NP,C6IP,C6N,C6A,C7NP,C7IP,C7N,C7A,C8NP,C8IP,C8N,C8A,C9NP,C9IP,C9N,C9A,C10NP,C10IP,C10N,C10A
0,0.074427,0.031606,0.013254,4.270873,1.393718,2.318445,0.403740,10.797998,7.753637,5.960258,2.855745,10.390180,11.102841,5.177248,4.288205,6.693311,10.346339,4.402394,3.386927,1.393718,5.563655,0.575023,0.806460
1,0.016224,0.008112,0.005070,2.415405,0.603344,1.671111,0.242352,10.320736,7.076873,5.394607,2.499569,10.648266,10.824706,5.045783,5.622763,7.824209,11.456443,4.379569,4.505308,1.488587,6.985611,0.489774,0.475577
2,0.012299,0.008132,0.004066,2.057360,0.401510,1.653817,0.234807,10.468751,7.056826,5.744141,2.638788,10.799108,11.087788,5.199307,5.790899,7.820815,11.632623,4.196039,4.381039,1.247224,6.689470,0.466565,0.408626

# y54

In [6]:
y54 = df.loc[64:64+54-1,1:].set_index(1).T.reset_index(drop=True).head(23).astype('float')

In [7]:
y54.head(3)

1,O2,METHANE,ETHANE,PROPANE,BUTANE,IPENTANE,PENTANE,T2PENTEN,CP,3MP,T2HEXENE,HEXANE,MCP,22MP,BENZENE,CH,223MB,4M1HEXEN,2MHX,1T3M,HEPTANE,H2O,MCH,ECP,23DM1HX,TOLUENE,2MHEPT,OCTANE,ECH,EBENZENE,PXYLENE,MXYLENE,OXYLENE,2MOCTN,1NONENE,NONANE,CUMENE,1T35TMCH,PCH,PRBENZEN,135MBENZ,1M2EBNZN,123MBENZ,24DMOCT,TEMH,3MN,TBCYHXAN,DECANE,ODEBZ,UNDECANE,PNBZ,DODECANE,HXBNZN,TRIDECAN
0,0.0,0.0,0.0,0.001580,0.003161,0.026233,0.074427,0.000632,0.013254,1.365843,0.027874,4.270873,1.504106,0.742696,0.403740,0.814338,0.816069,0.016279,6.178594,0.551714,10.797998,0.0,3.195887,2.212657,0.111028,2.855745,10.991813,10.390180,5.177248,1.018256,0.577619,1.425710,1.266621,10.083515,0.262824,6.693311,0.048004,2.641316,1.761078,0.204757,0.879322,1.299538,0.955306,0.935604,1.388203,3.239849,0.575023,1.168733,0.754120,0.221044,0.043843,0.003941,0.008497,0.0
1,0.0,0.0,0.0,0.000406,0.000811,0.006733,0.016224,0.000162,0.005070,0.591277,0.012067,2.415405,1.084145,0.677871,0.242352,0.586967,0.744840,0.014858,5.639305,0.499354,10.320736,0.0,2.892585,2.002668,0.108247,2.499569,10.716459,10.648266,5.045783,1.335153,0.757383,1.869413,1.660813,11.165419,0.291024,7.824209,0.063855,2.627622,1.751948,0.272369,1.169678,1.728653,1.270753,1.174725,1.742999,4.067887,0.489774,1.248288,0.444712,0.236091,0.025855,0.004209,0.005011,0.0
2,0.0,0.0,0.0,0.000407,0.000813,0.006749,0.012299,0.000163,0.004066,0.393480,0.008030,2.057360,1.072925,0.675951,0.234807,0.580892,0.742730,0.014816,5.623330,0.531709,10.468751,0.0,3.080005,2.132427,0.110878,2.638788,10.976911,10.799108,5.199307,1.375078,0.780031,1.925314,1.710477,11.337124,0.295499,7.820815,0.062094,2.517508,1.678530,0.264856,1.137415,1.680971,1.235702,1.124925,1.669108,3.895437,0.466565,1.045887,0.382106,0.197810,0.022215,0.003527,0.004305,0.0

# W = inv(X)@Y

In [8]:
W = np.linalg.inv(y23.values)@y54.values
print(W.shape)

(23, 54)

# build transform23to54

In [9]:
class transform_2354(object):
    def __init__(self):
        self.x_cols = y23.columns.tolist()
        self.y_cols = y54.columns.tolist()
        self.W = W
    
    def __call__(self,x):
        res = x.values@self.W
        return pd.DataFrame(res,columns=self.y_cols)

In [10]:
tr = transform_2354()

# make pred54

In [11]:
y54_pred = tr(y23)

# check ouput

In [12]:
y54_pred.head()

,O2,METHANE,ETHANE,PROPANE,BUTANE,IPENTANE,PENTANE,T2PENTEN,CP,3MP,T2HEXENE,HEXANE,MCP,22MP,BENZENE,CH,223MB,4M1HEXEN,2MHX,1T3M,HEPTANE,H2O,MCH,ECP,23DM1HX,TOLUENE,2MHEPT,OCTANE,ECH,EBENZENE,PXYLENE,MXYLENE,OXYLENE,2MOCTN,1NONENE,NONANE,CUMENE,1T35TMCH,PCH,PRBENZEN,135MBENZ,1M2EBNZN,123MBENZ,24DMOCT,TEMH,3MN,TBCYHXAN,DECANE,ODEBZ,UNDECANE,PNBZ,DODECANE,HXBNZN,TRIDECAN
0,0.0,0.0,0.0,0.001580,0.003161,0.026233,0.074427,0.000632,0.013254,1.365843,0.027874,4.270873,1.504106,0.742696,0.403740,0.814338,0.816069,0.016279,6.178594,0.551714,10.797998,0.0,3.195887,2.212657,0.111028,2.855745,10.991813,10.390180,5.177248,1.018256,0.577619,1.425710,1.266621,10.083515,0.262824,6.693311,0.048004,2.641316,1.761078,0.204757,0.879322,1.299538,0.955306,0.935604,1.388203,3.239849,0.575023,1.168733,0.754120,0.221044,0.043843,0.003941,0.008497,0.0
1,0.0,0.0,0.0,0.000406,0.000811,0.006733,0.016224,0.000162,0.005070,0.591277,0.012067,2.415405,1.084145,0.677871,0.242352,0.586967,0.744840,0.014858,5.639305,0.499354,10.320736,0.0,2.892585,2.002668,0.108247,2.499569,10.716459,10.648266,5.045783,1.335153,0.757383,1.869413,1.660813,11.165419,0.291024,7.824209,0.063855,2.627622,1.751948,0.272369,1.169678,1.728653,1.270753,1.174725,1.742999,4.067887,0.489774,1.248288,0.444712,0.236091,0.025855,0.004209,0.005011,0.0
2,0.0,0.0,0.0,0.000407,0.000813,0.006749,0.012299,0.000163,0.004066,0.393480,0.008030,2.057360,1.072925,0.675951,0.234807,0.580892,0.742730,0.014816,5.623330,0.531709,10.468751,0.0,3.080005,2.132427,0.110878,2.638788,10.976911,10.799108,5.199307,1.375078,0.780031,1.925314,1.710477,11.337124,0.295499,7.820815,0.062094,2.517508,1.678530,0.264856,1.137415,1.680971,1.235702,1.124925,1.669108,3.895437,0.466565,1.045887,0.382106,0.197810,0.022215,0.003527,0.004305,0.0
3,0.0,0.0,0.0,0.075747,0.151494,1.257398,1.441407,0.030299,0.127924,2.751123,0.056145,2.840508,1.453328,1.074246,0.867262,0.786846,1.180374,0.023546,8.936806,0.578173,10.358790,0.0,3.349153,2.318770,0.101432,2.837487,10.041802,8.565845,4.956788,1.182276,0.670662,1.655363,1.470648,8.962785,0.233613,5.766635,0.047426,2.274720,1.516653,0.202293,0.868737,1.283896,0.943807,0.777653,1.153844,2.692891,0.438164,0.817641,0.673458,0.154642,0.039153,0.002757,0.007588,0.0
4,0.0,0.0,0.0,0.086548,0.173096,1.436693,1.683546,0.034619,0.146264,3.191999,0.065143,3.525460,1.619667,1.083128,0.964332,0.876904,1.190133,0.023741,9.010697,0.611121,10.210216,0.0,3.540011,2.450910,0.096453,2.798176,9.548882,8.379398,5.139404,1.169119,0.663198,1.636941,1.454282,8.662017,0.225773,5.508594,0.044864,2.180541,1.453860,0.191362,0.821795,1.214520,0.892808,0.726013,1.077222,2.514067,0.454931,0.632719,0.436724,0.119667,0.025390,0.002133,0.004921,0.0

In [13]:
y54.head()

1,O2,METHANE,ETHANE,PROPANE,BUTANE,IPENTANE,PENTANE,T2PENTEN,CP,3MP,T2HEXENE,HEXANE,MCP,22MP,BENZENE,CH,223MB,4M1HEXEN,2MHX,1T3M,HEPTANE,H2O,MCH,ECP,23DM1HX,TOLUENE,2MHEPT,OCTANE,ECH,EBENZENE,PXYLENE,MXYLENE,OXYLENE,2MOCTN,1NONENE,NONANE,CUMENE,1T35TMCH,PCH,PRBENZEN,135MBENZ,1M2EBNZN,123MBENZ,24DMOCT,TEMH,3MN,TBCYHXAN,DECANE,ODEBZ,UNDECANE,PNBZ,DODECANE,HXBNZN,TRIDECAN
0,0.0,0.0,0.0,0.001580,0.003161,0.026233,0.074427,0.000632,0.013254,1.365843,0.027874,4.270873,1.504106,0.742696,0.403740,0.814338,0.816069,0.016279,6.178594,0.551714,10.797998,0.0,3.195887,2.212657,0.111028,2.855745,10.991813,10.390180,5.177248,1.018256,0.577619,1.425710,1.266621,10.083515,0.262824,6.693311,0.048004,2.641316,1.761078,0.204757,0.879322,1.299538,0.955306,0.935604,1.388203,3.239849,0.575023,1.168733,0.754120,0.221044,0.043843,0.003941,0.008497,0.0
1,0.0,0.0,0.0,0.000406,0.000811,0.006733,0.016224,0.000162,0.005070,0.591277,0.012067,2.415405,1.084145,0.677871,0.242352,0.586967,0.744840,0.014858,5.639305,0.499354,10.320736,0.0,2.892585,2.002668,0.108247,2.499569,10.716459,10.648266,5.045783,1.335153,0.757383,1.869413,1.660813,11.165419,0.291024,7.824209,0.063855,2.627622,1.751948,0.272369,1.169678,1.728653,1.270753,1.174725,1.742999,4.067887,0.489774,1.248288,0.444712,0.236091,0.025855,0.004209,0.005011,0.0
2,0.0,0.0,0.0,0.000407,0.000813,0.006749,0.012299,0.000163,0.004066,0.393480,0.008030,2.057360,1.072925,0.675951,0.234807,0.580892,0.742730,0.014816,5.623330,0.531709,10.468751,0.0,3.080005,2.132427,0.110878,2.638788,10.976911,10.799108,5.199307,1.375078,0.780031,1.925314,1.710477,11.337124,0.295499,7.820815,0.062094,2.517508,1.678530,0.264856,1.137415,1.680971,1.235702,1.124925,1.669108,3.895437,0.466565,1.045887,0.382106,0.197810,0.022215,0.003527,0.004305,0.0
3,0.0,0.0,0.0,0.075747,0.151494,1.257398,1.441407,0.030299,0.127924,2.751123,0.056145,2.840508,1.453328,1.074246,0.867262,0.786846,1.180374,0.023546,8.936806,0.578173,10.358790,0.0,3.349153,2.318770,0.101432,2.837487,10.041802,8.565845,4.956788,1.182276,0.670662,1.655363,1.470648,8.962785,0.233613,5.766635,0.047426,2.274720,1.516653,0.202293,0.868737,1.283896,0.943807,0.777653,1.153844,2.692891,0.438164,0.817641,0.673458,0.154642,0.039153,0.002757,0.007588,0.0
4,0.0,0.0,0.0,0.086548,0.173096,1.436693,1.683546,0.034619,0.146264,3.191999,0.065143,3.525460,1.619667,1.083128,0.964332,0.876904,1.190133,0.023741,9.010697,0.611121,10.210216,0.0,3.540011,2.450910,0.096453,2.798176,9.548882,8.379398,5.139404,1.169119,0.663198,1.636941,1.454282,8.662017,0.225773,5.508594,0.044864,2.180541,1.453860,0.191362,0.821795,1.214520,0.892808,0.726013,1.077222,2.514067,0.454931,0.632719,0.436724,0.119667,0.025390,0.002133,0.004921,0.0

In [14]:
t = y54.values-y54_pred.values
t = pd.DataFrame(t,columns=y54.columns).apply(lambda x:round(x,6))
print(np.sum(t.values.tolist()))

0.0

# save TR

In [15]:
joblib.dump(tr,'../model/transformer(23_to_54).pkl')
print('save done!')

save done!