In [1]:
from API.utils import *
import joblib
col_names = joblib.load('./data/phase_2/cleaned/col_names.pkl')
eva = EVA()

## 準備輸入資料

In [2]:
x4 = pd.read_csv('./data/phase_1/test_170.csv',index_col=0).sample(1)[['T10','T50','T90','N+A']].reset_index(drop=True)

In [3]:
case4 = pd.read_csv('./data/phase_2/cleaned/train.csv',index_col=0)[col_names['case']].sample(1).reset_index(drop=True)

In [4]:
Input = x4.join(case4)
Input

,T10,T50,T90,N+A,Case Conditions_Feed Rate to C013 (Input)_m3/hr,Case Conditions_Heart Cut Prod. Rate (Input)_m3/hr,Case Conditions_C7+ in Light End (Input)_wt%,Case Conditions_C6P- in Heart Cut (Input)_wt%
0,95.1,117.4,145.1,49.185,30.0,100.0,10.0,0.25

## 呼叫eva得到結果

In [5]:
eva(Input)

In [6]:
eva.predict

,HYD,NC1,NC2,NC3,PC4,SAP,SAN,BEZ,TOL,ETB,PXY,MXY,OXY,C9A,C10,Light End Product Properties_Light End Prod. Rate_m3/hr,Heavy End Product Properties_Heavy End Product Rate_m3/hr,Duty_E062 3.5K Steam Rate_ton/hr,Duty_Reboiler Heat Duty_Mkcal/hr
0,0.0,0.0,0.0,0.000757,0.002127,47.797708,37.430802,0.030073,4.262521,1.903864,1.082345,2.670238,2.370034,2.283961,0.165571,68.494159,36.635631,1.1113,-1.015013

In [7]:
eva.naphtha

,C5NP,C5IP,C5N,C6NP,C6IP,C6N,C6A,C7NP,C7IP,C7N,...,C8N,C8A,C9NP,C9IP,C9N,C9A,C10NP,C10IP,C10N,C10A
0,1.838323,1.228078,0.245411,3.32912,3.013079,4.942511,0.617808,5.268493,4.473344,13.888379,...,9.557561,6.253638,3.963658,8.209891,5.709574,3.226989,1.112188,4.495362,0.796347,0.635691

In [8]:
eva.pre_d

,Individual Component to Light End Split Factor_Oxygen_Ratio,Individual Component to Heart Cut Split Factor_Oxygen_Ratio,Individual Component to Heavy End Split Factor_Oxygen_Ratio,Individual Component to Light End Split Factor_Methane_Ratio,Individual Component to Heart Cut Split Factor_Methane_Ratio,Individual Component to Heavy End Split Factor_Methane_Ratio,Individual Component to Light End Split Factor_Ethane_Ratio,Individual Component to Heart Cut Split Factor_Ethane_Ratio,Individual Component to Heavy End Split Factor_Ethane_Ratio,Individual Component to Light End Split Factor_Propane_Ratio,...,Individual Component to Heavy End Split Factor_n-Pentylbenzene_Ratio,Individual Component to Light End Split Factor_n-Dodecane_Ratio,Individual Component to Heart Cut Split Factor_n-Dodecane_Ratio,Individual Component to Heavy End Split Factor_n-Dodecane_Ratio,Individual Component to Light End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heart Cut Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heavy End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Light End Split Factor_n-Tridecane_Ratio,Individual Component to Heart Cut Split Factor_n-Tridecane_Ratio,Individual Component to Heavy End Split Factor_n-Tridecane_Ratio
0,0.997141,0.00119,0.001669,0.99665,0.000876,0.002475,0.997473,0.00099,0.001537,0.989788,...,0.795374,0.000003,0.189805,0.810193,0.000995,0.209007,0.789998,0.000627,0.00056,0.998813

In [9]:
eva.reform

,Hydrogen,Methane,Ethane,Propane,n-Butane,i-Butane,C4 Naphthenes,n-Pentane,C5 i-Paraffins,C5 Naphthenes,...,M-Xylene,O-Xylene,n-Nonane,C9 i-Paraffins,C9 Naphthenes,C9 Aromtics,C10+ n-Paraffins,C10+ i-Paraffins,C10+ Naphthenes,C10+ Aromtics
0,0.0,0.0,0.0,0.000757,0.000896,0.001231,0.000112,0.047958,0.018569,0.011415,...,2.670238,2.370034,5.047824,10.520372,6.718275,2.283961,0.331219,2.900869,0.260242,0.165571