In [1]:
from API.utils import EVA
from API.utils import *
import joblib

In [2]:
col_names = joblib.load('./data/phase_2/cleaned/col_names.pkl')
eva = EVA()

## 準備輸入資料

In [3]:
x4 = pd.read_csv('./data/phase_1/test_170.csv',index_col=0).sample(1)[['T10','T50','T90','N+A']].reset_index(drop=True)

In [4]:
case4 = pd.read_csv('./data/phase_2/cleaned/train.csv',index_col=0)[col_names['case']].sample(1).reset_index(drop=True)

In [5]:
Input = x4.join(case4)
Input

,T10,T50,T90,N+A,Case Conditions_Feed Rate to C013 (Input)_m3/hr,Case Conditions_C7+ in Light End (Input)_wt%,Case Conditions_Heart Cut Prod. Rate (Input)_m3/hr,Case Conditions_C6P- in Heart Cut (Input)_wt%
0,105.6,121.7,145.8,31.642,10.0,10.0,100.0,2.0

## 呼叫eva得到結果

In [6]:
eva(Input)

In [7]:
eva.predict

,HYD,NC1,NC2,NC3,PC4,SAP,SAN,BEZ,TOL,ETB,PXY,MXY,OXY,C9A,C10,Light End Product Properties_Light End Prod. Rate_ton/hr,Heavy End Product Properties_Heavy End Product Rate_ton/hr,Duty_E062 3.5K Steam Rate_ton/hr,Duty_Reboiler Heat Duty_Mkcal/hr
0,1840.163818,648.642883,3711.360596,1546.156128,935.698853,14056.428894,1611.268013,1373.370728,11119.987305,2835.309082,1778.949219,11977.572266,4395.80957,12883.287109,3332.517822,8743.837139,18628.151565,5.243383,6.264647

In [8]:
eva.naphtha

,C5NP,C5IP,C5N,C6NP,C6IP,C6N,C6A,C7NP,C7IP,C7N,...,C8N,C8A,C9NP,C9IP,C9N,C9A,C10NP,C10IP,C10N,C10A
0,0.067557,0.076078,0.099851,3.368622,1.033056,2.108415,0.425503,10.767035,7.755392,6.226613,...,4.969145,5.687548,6.932461,10.997079,4.448762,3.797269,0.986327,5.829079,0.526091,0.429199

In [9]:
eva.pre_d

,Individual Component to Light End Split Factor_Oxygen_Ratio,Individual Component to Heart Cut Split Factor_Oxygen_Ratio,Individual Component to Heavy End Split Factor_Oxygen_Ratio,Individual Component to Light End Split Factor_Methane_Ratio,Individual Component to Heart Cut Split Factor_Methane_Ratio,Individual Component to Heavy End Split Factor_Methane_Ratio,Individual Component to Light End Split Factor_Ethane_Ratio,Individual Component to Heart Cut Split Factor_Ethane_Ratio,Individual Component to Heavy End Split Factor_Ethane_Ratio,Individual Component to Light End Split Factor_Propane_Ratio,...,Individual Component to Heavy End Split Factor_n-Pentylbenzene_Ratio,Individual Component to Light End Split Factor_n-Dodecane_Ratio,Individual Component to Heart Cut Split Factor_n-Dodecane_Ratio,Individual Component to Heavy End Split Factor_n-Dodecane_Ratio,Individual Component to Light End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heart Cut Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heavy End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Light End Split Factor_n-Tridecane_Ratio,Individual Component to Heart Cut Split Factor_n-Tridecane_Ratio,Individual Component to Heavy End Split Factor_n-Tridecane_Ratio
0,0.999094,0.000676,0.00023,0.999213,0.000517,0.00027,0.998843,0.000531,0.000626,0.987172,...,0.341472,0.000025,0.649279,0.350696,0.000721,0.645229,0.35405,0.000551,0.000271,0.999178

In [10]:
eva.reform

,Product Hydrogen,Product Methane,Product Ethane,Product Propane,Product n-Butane,Product i-Butane,Product C4 Naphthenes,Product n-Pentane,Product C5 i-Paraffins,Product C5 Naphthenes,...,Product M-Xylene,Product O-Xylene,Product n-Nonane,Product C9 i-Paraffins,Product C9 Naphthenes,Product C9 Aromtics,Product C10+ n-Paraffins,Product C10+ i-Paraffins,Product C10+ Naphthenes,Product C10+ Aromtics
0,1840.163818,648.642883,3711.360596,1546.156128,500.473419,435.225433,0.0,1003.610352,1578.053833,183.932114,...,11977.572266,4395.80957,74.209396,256.585663,49.153206,12883.287109,203.544235,262.114929,196.151993,3332.517822